name: Conditional Workflow for New Files
on:
  push:
    paths:
      - app.py

jobs:
  condition:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build and Test
        uses: actions/trigger-workflow@v1
        with:
          workflow: build-test.yml
