name: Hello World Workflow

on:
  push:
    branches:
      - main # Replace 'main' with your branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello, world!"
